### ISSUE TITLE
Question n'ayant rien à voir avec le projet dépoosé sur Git

### ISSUE THREAD

**Issue by DarckCrystale** [davidonet/bugNbuzz#13]
Bonjour,
Je cherche à joindre wargreen (vu que le site du bib est hs, je suppose que les adresses mails en @bib ne fonctionnent plus non plus).
Vous pouvez me joindre à : vraken@live.fr
Merci d'avance ! (et désolée pour le dérangement)

**Comment by wargreen** [comment]
Salut,
Le serveur mais tourne, n'hésite pas à me contacter par là.
