### ISSUE TITLE
XOSC ping

### ISSUE THREAD

**Issue by wargreen** [davidonet/bugNbuzz#8]
Le temps de réponse du X-OSC n'est vraiment pas stable :
mac (filaire) -> box -> xosc
MacBook-Pro-de-cie:~ cieconcordance$ ping 192.168.0.30
PING 192.168.0.30 (192.168.0.30): 56 data bytes
64 bytes from 192.168.0.30: icmp_seq=0 ttl=100 time=19.432 ms
64 bytes from 192.168.0.30: icmp_seq=1 ttl=100 time=9.515 ms
64 bytes from 192.168.0.30: icmp_seq=2 ttl=100 time=7.608 ms
Request timeout for icmp_seq 3
64 bytes from 192.168.0.30: icmp_seq=4 ttl=100 time=7.036 ms
64 bytes from 192.168.0.30: icmp_seq=5 ttl=100 time=15.969 ms
64 bytes from 192.168.0.30: icmp_seq=6 ttl=100 time=6.276 ms
64 bytes from 192.168.0.30: icmp_seq=7 ttl=100 time=6.220 ms
64 bytes from 192.168.0.30: icmp_seq=8 ttl=100 time=7.344 ms
64 bytes from 192.168.0.30: icmp_seq=9 ttl=100 time=12.715 ms
64 bytes from 192.168.0.30: icmp_seq=10 ttl=100 time=6.993 ms
64 bytes from 192.168.0.30: icmp_seq=11 ttl=100 time=5.867 ms
64 bytes from 192.168.0.30: icmp_seq=12 ttl=100 time=8.013 ms
64 bytes from 192.168.0.30: icmp_seq=13 ttl=100 time=9.732 ms
64 bytes from 192.168.0.30: icmp_seq=14 ttl=100 time=15.242 ms
64 bytes from 192.168.0.30: icmp_seq=15 ttl=100 time=6.940 ms
64 bytes from 192.168.0.30: icmp_seq=16 ttl=100 time=5.876 ms
64 bytes from 192.168.0.30: icmp_seq=17 ttl=100 time=8.007 ms
64 bytes from 192.168.0.30: icmp_seq=18 ttl=100 time=17.364 ms
64 bytes from 192.168.0.30: icmp_seq=19 ttl=100 time=6.178 ms
64 bytes from 192.168.0.30: icmp_seq=20 ttl=100 time=5.883 ms
64 bytes from 192.168.0.30: icmp_seq=21 ttl=100 time=6.288 ms
64 bytes from 192.168.0.30: icmp_seq=22 ttl=100 time=7.813 ms
64 bytes from 192.168.0.30: icmp_seq=23 ttl=100 time=18.099 ms
64 bytes from 192.168.0.30: icmp_seq=24 ttl=100 time=6.031 ms
64 bytes from 192.168.0.30: icmp_seq=25 ttl=100 time=7.796 ms
64 bytes from 192.168.0.30: icmp_seq=26 ttl=100 time=8.143 ms
64 bytes from 192.168.0.30: icmp_seq=27 ttl=100 time=9.551 ms
64 bytes from 192.168.0.30: icmp_seq=28 ttl=100 time=8.504 ms
64 bytes from 192.168.0.30: icmp_seq=29 ttl=100 time=5.955 ms
64 bytes from 192.168.0.30: icmp_seq=30 ttl=100 time=9.045 ms
64 bytes from 192.168.0.30: icmp_seq=31 ttl=100 time=12.328 ms
64 bytes from 192.168.0.30: icmp_seq=32 ttl=100 time=16.918 ms
64 bytes from 192.168.0.30: icmp_seq=33 ttl=100 time=7.560 ms
64 bytes from 192.168.0.30: icmp_seq=34 ttl=100 time=7.692 ms
64 bytes from 192.168.0.30: icmp_seq=35 ttl=100 time=5.970 ms
64 bytes from 192.168.0.30: icmp_seq=36 ttl=100 time=9.531 ms
64 bytes from 192.168.0.30: icmp_seq=37 ttl=100 time=8.428 ms
64 bytes from 192.168.0.30: icmp_seq=38 ttl=100 time=8.679 ms
64 bytes from 192.168.0.30: icmp_seq=39 ttl=100 time=7.720 ms
64 bytes from 192.168.0.30: icmp_seq=40 ttl=100 time=8.106 ms
64 bytes from 192.168.0.30: icmp_seq=41 ttl=100 time=15.015 ms
64 bytes from 192.168.0.30: icmp_seq=42 ttl=100 time=8.068 ms
64 bytes from 192.168.0.30: icmp_seq=43 ttl=100 time=5.897 ms
64 bytes from 192.168.0.30: icmp_seq=44 ttl=100 time=6.198 ms
64 bytes from 192.168.0.30: icmp_seq=45 ttl=100 time=10.284 ms
64 bytes from 192.168.0.30: icmp_seq=46 ttl=100 time=6.743 ms
64 bytes from 192.168.0.30: icmp_seq=47 ttl=100 time=8.164 ms
64 bytes from 192.168.0.30: icmp_seq=48 ttl=100 time=6.151 ms
64 bytes from 192.168.0.30: icmp_seq=49 ttl=100 time=10.333 ms
64 bytes from 192.168.0.30: icmp_seq=50 ttl=100 time=18.987 ms
64 bytes from 192.168.0.30: icmp_seq=51 ttl=100 time=7.805 ms
64 bytes from 192.168.0.30: icmp_seq=52 ttl=100 time=16.858 ms
64 bytes from 192.168.0.30: icmp_seq=53 ttl=100 time=9.503 ms
64 bytes from 192.168.0.30: icmp_seq=54 ttl=100 time=18.327 ms
^C
--- 192.168.0.30 ping statistics ---
55 packets transmitted, 54 packets received, 1.8% packet loss
round-trip min/avg/max/stddev = 5.867/9.569/19.432/3.988 ms

mac (wifi) -> box :
MacBook-Pro-de-cie:~ cieconcordance$ ping 192.168.0.1
PING 192.168.0.1 (192.168.0.1): 56 data bytes
64 bytes from 192.168.0.1: icmp_seq=0 ttl=64 time=4.159 ms
Request timeout for icmp_seq 1
64 bytes from 192.168.0.1: icmp_seq=2 ttl=64 time=1.216 ms
64 bytes from 192.168.0.1: icmp_seq=3 ttl=64 time=1.748 ms
64 bytes from 192.168.0.1: icmp_seq=4 ttl=64 time=1.401 ms
64 bytes from 192.168.0.1: icmp_seq=5 ttl=64 time=7.034 ms
64 bytes from 192.168.0.1: icmp_seq=6 ttl=64 time=1.375 ms
64 bytes from 192.168.0.1: icmp_seq=7 ttl=64 time=1.621 ms
64 bytes from 192.168.0.1: icmp_seq=8 ttl=64 time=1.815 ms
64 bytes from 192.168.0.1: icmp_seq=9 ttl=64 time=2.240 ms
64 bytes from 192.168.0.1: icmp_seq=10 ttl=64 time=1.284 ms
64 bytes from 192.168.0.1: icmp_seq=11 ttl=64 time=1.315 ms
64 bytes from 192.168.0.1: icmp_seq=12 ttl=64 time=1.138 ms
64 bytes from 192.168.0.1: icmp_seq=13 ttl=64 time=1.965 ms
64 bytes from 192.168.0.1: icmp_seq=14 ttl=64 time=11.568 ms
64 bytes from 192.168.0.1: icmp_seq=15 ttl=64 time=2.441 ms
64 bytes from 192.168.0.1: icmp_seq=16 ttl=64 time=2.480 ms
64 bytes from 192.168.0.1: icmp_seq=17 ttl=64 time=1.514 ms
64 bytes from 192.168.0.1: icmp_seq=18 ttl=64 time=5.195 ms
64 bytes from 192.168.0.1: icmp_seq=19 ttl=64 time=4.712 ms
64 bytes from 192.168.0.1: icmp_seq=20 ttl=64 time=1.169 ms
64 bytes from 192.168.0.1: icmp_seq=21 ttl=64 time=1.238 ms
64 bytes from 192.168.0.1: icmp_seq=22 ttl=64 time=1.229 ms
64 bytes from 192.168.0.1: icmp_seq=23 ttl=64 time=13.251 ms
64 bytes from 192.168.0.1: icmp_seq=24 ttl=64 time=2.196 ms
64 bytes from 192.168.0.1: icmp_seq=25 ttl=64 time=2.197 ms
64 bytes from 192.168.0.1: icmp_seq=26 ttl=64 time=1.226 ms
64 bytes from 192.168.0.1: icmp_seq=27 ttl=64 time=5.441 ms
64 bytes from 192.168.0.1: icmp_seq=28 ttl=64 time=1.278 ms
64 bytes from 192.168.0.1: icmp_seq=29 ttl=64 time=1.770 ms
64 bytes from 192.168.0.1: icmp_seq=30 ttl=64 time=1.198 ms
64 bytes from 192.168.0.1: icmp_seq=31 ttl=64 time=1.207 ms
64 bytes from 192.168.0.1: icmp_seq=32 ttl=64 time=1.443 ms
64 bytes from 192.168.0.1: icmp_seq=33 ttl=64 time=1.145 ms
64 bytes from 192.168.0.1: icmp_seq=34 ttl=64 time=1.707 ms
64 bytes from 192.168.0.1: icmp_seq=35 ttl=64 time=23.158 ms
64 bytes from 192.168.0.1: icmp_seq=36 ttl=64 time=9.995 ms
64 bytes from 192.168.0.1: icmp_seq=37 ttl=64 time=1.248 ms
64 bytes from 192.168.0.1: icmp_seq=38 ttl=64 time=2.130 ms
64 bytes from 192.168.0.1: icmp_seq=39 ttl=64 time=1.794 ms
64 bytes from 192.168.0.1: icmp_seq=40 ttl=64 time=2.028 ms
64 bytes from 192.168.0.1: icmp_seq=41 ttl=64 time=26.117 ms
64 bytes from 192.168.0.1: icmp_seq=42 ttl=64 time=1.597 ms
64 bytes from 192.168.0.1: icmp_seq=43 ttl=64 time=1.202 ms
64 bytes from 192.168.0.1: icmp_seq=44 ttl=64 time=1.244 ms
64 bytes from 192.168.0.1: icmp_seq=45 ttl=64 time=23.152 ms
64 bytes from 192.168.0.1: icmp_seq=46 ttl=64 time=1.286 ms
64 bytes from 192.168.0.1: icmp_seq=47 ttl=64 time=1.143 ms
64 bytes from 192.168.0.1: icmp_seq=48 ttl=64 time=1.702 ms
64 bytes from 192.168.0.1: icmp_seq=49 ttl=64 time=5.949 ms
64 bytes from 192.168.0.1: icmp_seq=50 ttl=64 time=2.471 ms
64 bytes from 192.168.0.1: icmp_seq=51 ttl=64 time=2.488 ms
64 bytes from 192.168.0.1: icmp_seq=52 ttl=64 time=3.341 ms
64 bytes from 192.168.0.1: icmp_seq=53 ttl=64 time=3.007 ms
64 bytes from 192.168.0.1: icmp_seq=54 ttl=64 time=2.800 ms
64 bytes from 192.168.0.1: icmp_seq=55 ttl=64 time=9.753 ms
64 bytes from 192.168.0.1: icmp_seq=56 ttl=64 time=2.415 ms
64 bytes from 192.168.0.1: icmp_seq=57 ttl=64 time=2.375 ms
64 bytes from 192.168.0.1: icmp_seq=58 ttl=64 time=9.548 ms
64 bytes from 192.168.0.1: icmp_seq=59 ttl=64 time=1.450 ms
64 bytes from 192.168.0.1: icmp_seq=60 ttl=64 time=1.238 ms
64 bytes from 192.168.0.1: icmp_seq=61 ttl=64 time=1.240 ms
64 bytes from 192.168.0.1: icmp_seq=62 ttl=64 time=5.010 ms
64 bytes from 192.168.0.1: icmp_seq=63 ttl=64 time=1.433 ms
^C
--- 192.168.0.1 ping statistics ---
65 packets transmitted, 64 packets received, 1.5% packet loss
round-trip min/avg/max/stddev = 1.138/3.977/26.117/5.256 ms

Pas des plus stable, mais correct.
Mêmes types de pic de latences depuis la tablette vers la passerelle. Un WRT reglerais peut-être ça ?

**Comment by davidonet** [comment]
J'ai constaté en effet que le routeur numericable avait du mal à gérer peut être parce qu'il y a qu'une antenne. Comme le xosc balance pas mal de trame en broadcast il doit pas aimer.
Le wrt devrait résoudre le pb d'autant plus que le mac sera en ethernet...

**Comment by wargreen** [comment]
Après passage via le WRT, c'est peut-être un peu plus stable, mais on a toujours des pics :
mac (eth) > wrt > xosc

MacBook-Pro-de-cie:bugNbuzz cieconcordance$ ping 192.168.1.30
PING 192.168.1.30 (192.168.1.30): 56 data bytes
64 bytes from 192.168.1.30: icmp_seq=0 ttl=100 time=6.050 ms
64 bytes from 192.168.1.30: icmp_seq=1 ttl=100 time=12.250 ms
64 bytes from 192.168.1.30: icmp_seq=2 ttl=100 time=5.833 ms
64 bytes from 192.168.1.30: icmp_seq=3 ttl=100 time=5.997 ms
64 bytes from 192.168.1.30: icmp_seq=4 ttl=100 time=14.991 ms
64 bytes from 192.168.1.30: icmp_seq=5 ttl=100 time=8.255 ms
64 bytes from 192.168.1.30: icmp_seq=6 ttl=100 time=5.812 ms
64 bytes from 192.168.1.30: icmp_seq=7 ttl=100 time=14.837 ms
64 bytes from 192.168.1.30: icmp_seq=8 ttl=100 time=5.892 ms
64 bytes from 192.168.1.30: icmp_seq=9 ttl=100 time=6.249 ms
64 bytes from 192.168.1.30: icmp_seq=10 ttl=100 time=5.807 ms
64 bytes from 192.168.1.30: icmp_seq=11 ttl=100 time=7.920 ms
64 bytes from 192.168.1.30: icmp_seq=12 ttl=100 time=6.093 ms
64 bytes from 192.168.1.30: icmp_seq=13 ttl=100 time=15.087 ms
64 bytes from 192.168.1.30: icmp_seq=14 ttl=100 time=7.966 ms
64 bytes from 192.168.1.30: icmp_seq=15 ttl=100 time=11.117 ms
64 bytes from 192.168.1.30: icmp_seq=16 ttl=100 time=9.635 ms
64 bytes from 192.168.1.30: icmp_seq=17 ttl=100 time=6.926 ms
64 bytes from 192.168.1.30: icmp_seq=18 ttl=100 time=5.853 ms
64 bytes from 192.168.1.30: icmp_seq=19 ttl=100 time=5.876 ms
64 bytes from 192.168.1.30: icmp_seq=20 ttl=100 time=7.843 ms
64 bytes from 192.168.1.30: icmp_seq=21 ttl=100 time=5.916 ms
64 bytes from 192.168.1.30: icmp_seq=22 ttl=100 time=83.897 ms
64 bytes from 192.168.1.30: icmp_seq=23 ttl=100 time=5.873 ms
64 bytes from 192.168.1.30: icmp_seq=24 ttl=100 time=8.113 ms
64 bytes from 192.168.1.30: icmp_seq=25 ttl=100 time=13.893 ms
64 bytes from 192.168.1.30: icmp_seq=26 ttl=100 time=8.217 ms
64 bytes from 192.168.1.30: icmp_seq=27 ttl=100 time=5.817 ms
64 bytes from 192.168.1.30: icmp_seq=28 ttl=100 time=5.862 ms
64 bytes from 192.168.1.30: icmp_seq=29 ttl=100 time=13.332 ms
64 bytes from 192.168.1.30: icmp_seq=30 ttl=100 time=7.394 ms
64 bytes from 192.168.1.30: icmp_seq=31 ttl=100 time=6.040 ms
64 bytes from 192.168.1.30: icmp_seq=32 ttl=100 time=6.673 ms
64 bytes from 192.168.1.30: icmp_seq=33 ttl=100 time=5.848 ms
64 bytes from 192.168.1.30: icmp_seq=34 ttl=100 time=6.184 ms
64 bytes from 192.168.1.30: icmp_seq=35 ttl=100 time=11.924 ms
64 bytes from 192.168.1.30: icmp_seq=36 ttl=100 time=6.632 ms
64 bytes from 192.168.1.30: icmp_seq=37 ttl=100 time=6.084 ms
64 bytes from 192.168.1.30: icmp_seq=38 ttl=100 time=16.818 ms
64 bytes from 192.168.1.30: icmp_seq=39 ttl=100 time=6.282 ms
64 bytes from 192.168.1.30: icmp_seq=40 ttl=100 time=13.947 ms
64 bytes from 192.168.1.30: icmp_seq=41 ttl=100 time=11.426 ms
^C
--- 192.168.1.30 ping statistics ---
42 packets transmitted, 42 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 5.807/10.297/83.897/11.955 ms

**Comment by davidonet** [comment]
J'ai réduis la fréquence de rafraîchissement des led ce qui devrait libérer de la bande passante.
On peut également réduire la fréquence d'envois des potars.
Je pense que ça devrait le faire
