### ISSUE TITLE
OSC4Bitwig bank & groups

### ISSUE THREAD

**Issue by wargreen** [davidonet/bugNbuzz#9]
L'organisation des tracks en banks via OSC4Bitwig, et l'acces aux tracks filles d'un groupe rendent difficile les acces directs aux parametres. Est-t-il envisageable de créer un controller script complet, sans tout recommencer de zero ?

**Comment by davidonet** [comment]
Non je pense que ça n'est pas envisageable.
Quand on voit la complexité de OSC4Bitwig, c'est un travail énorme qui demande un gros boulot d'apprentissage de l'API Bitwig.
Je me lancerai pas la dedans...

**Comment by wargreen** [comment]
Passage à ardour, c'est plus simple...
